#!/bin/sh

# Setup command $1 as an alternative to $2 (if $1 is present)
set_alt() {
	[ -x "$(command -v "$1")" ] && alias "$2"="$1"
}

set_alt nvim vim
set_alt nvim vi
set_alt fd find
set_alt fd find
set_alt eza ls

alias "v"="$EDITOR"
alias "e"="$EDITOR"

# Shorten long commands
alias "g"="git"
alias "ga"="git add -A"
alias "gac"="git add -A && git commit"
alias "gap"="git add -p"
alias "gco"="git commit"
alias "gst"="git status"
alias "p"="sudo pacman"

# Verbosity and settings that you pretty much just always are going to want.
alias cp="cp -iv" 
alias mv="mv -iv" 
alias rm="rm -vI" 
alias bc="bc -ql" 
alias rsync="rsync -vrPlu" 
alias mkdir="mkdir -v" 
alias yt="yt-dlp --embed-metadata -i" 
alias ytv="yt -S res,ext:mp4:m4a --recode mp4" 
alias yta="yt -x -f bestaudio/best --audio-format mp3" 
alias ytt="yt --skip-download --write-thumbnail" 
alias ffmpeg="ffmpeg -hide_banner"
alias stow="stow -v"
[ -z "$(alias ls)" ] && alias ls="ls --color=auto --group-directories-first -h"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
