hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("mpd")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("steam -silent")
    hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
end)

-- runs on config reload too (equivalent to exec, not exec-once)
hl.on("config.reloaded", function()
    hl.exec_cmd('gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"')
end)
